version: "3.8"
services:
  netstream:
    image: postgres:16.1-bullseye
    container_name: netstream
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "9255:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./:/docker-entrypoint-initdb.d
volumes:
  postgresdata:
    driver: local
